name: Push Frontend Image to GHCR and Deploy to VPS
run-name: Release Image GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} -t ghcr.io/vsalcode/fgo24-react-cinevo:latest .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/vsalcode/fgo24-react-cinevo:latest

  deploy:
    name: Deploy to VPS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Connect & Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 146.190.102.54
          username: faisal
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 9401
          script: |
            echo "Pulling latest image from GHCR..."
            echo "${{ secrets.APP_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/vsalcode/fgo24-react-cinevo:latest
            echo "Stopping and removing existing containers..."
            docker compose down || true
            echo "Checking for port conflicts..."
            if sudo lsof -i :9402; then
              echo "Freeing port 9402..."
              sudo kill -9 $(sudo lsof -t -i :9402) || true
            fi
            echo "Starting new deployment..."
            docker compose up -d